name: gravity_ui_shell # Changed name
description: A visual Flutter prototype of the Gravity shopping app UI.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Use a recent SDK version

dependencies:
  flutter:
    sdk: flutter

  # Core UI & Utilities
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1 # Efficient image loading and caching
  smooth_page_indicator: ^1.1.0 # Dots for PageView (carousel)
  flutter_svg: ^2.0.9 # For SVG logos (like Saks)
  url_launcher: ^6.2.5 # For external links (merchant)
  intl: ^0.18.1 # For currency formatting (using 0.18.1 for wider compatibility)

  # Navigation
  go_router: ^12.1.1 # Declarative routing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true